### ISSUE TITLE
Display Filenames for Uploaded Header Images

### ISSUE THREAD

**Issue by balazsvincze** [ttimot24/HorizontCMS#10]
When I have similar images uploaded for header images it is hard to differentiate them. It would be useful to add the filenames

![image](https://user-images.githubusercontent.com/5154742/39429629-bb29462c-4c8b-11e8-8eff-96bc6380350f.png)

**Comment by ttimot24** [comment]
Done in 4bc06d2b84d2536de909f17269fcdda7fceb69e0 and 1bc637be30e93c51914d6c1e6244a2323c7af002
