### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by Nowi5** [ttimot24/HorizontCMS#15]
Dear Ttimot24,

thank you very much for working on the CMS, I would like to see the features you have build by following your links:
Frontend: https://horizontcms.herokuapp.com/
Backend: https://horizontcms.herokuapp.com/admin
Unfortunately that leads only to a installation page and I'm not aware of your MySQL settings,....

Thank you for having a look.

**Comment by ttimot24** [comment]
Hi Nowi5,

Thank you for your interest in my CMS. I fixed the wrong credentials, which was the root cause why you were redirected to the install page. Now you can try again.
