### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by JamieSlome** [ttimot24/HorizontCMS#45]
Hey there!

I belong to an open source security research community, and a member (@dota-st) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by ttimot24** [comment]
Hi @JamieSlome!

I created a security.md file. Right now please feel free to open issue tickets about security problems, since the platform still in beta version.

Later I'll create an email where security problems can be reported. I'll keep you updated.

Thank you!

**Comment by JamieSlome** [comment]
@ttimot24 - thanks for your response 👍 

You can view the report directly here:
https://huntr.dev/bounties/1d70e354-b8f3-41a4-98bb-7b4e9770af38/

It is private and only accessible to maintainers with repository write permissions!
