### ISSUE TITLE
Error when trying to change User role settings

### ISSUE THREAD

**Issue by balazsvincze** [ttimot24/HorizontCMS#6]
![image](https://user-images.githubusercontent.com/5154742/39410804-36c91f84-4bfe-11e8-9b60-13575fbc0a58.png)

**Comment by ttimot24** [comment]
Fixed in commit 15404b54de7acc2592ecbfd027c0efa26f162588

**Comment by balazsvincze** [comment]
I have created a test user and added all priviliges to the user role but looks like I can't login with it to the admin pages

**Comment by ttimot24** [comment]
You have to bind the Role to the user. User can login into admin panel with Role that has AdminArea privilage.

**Comment by balazsvincze** [comment]
I created the test user as User so I assumed that it is going to be User by default and I don't have to set anything else.

**Comment by ttimot24** [comment]
There's a missunderstand here. When you create a new user, there's a dropdown on the page where you can select the role of the user.
