### ISSUE TITLE
Youtube plugin slider showing different image than the thumbnail set for the video

### ISSUE THREAD

**Issue by balazsvincze** [ttimot24/HorizontCMS#7]
![image](https://user-images.githubusercontent.com/5154742/39425917-e95e3e34-4c7d-11e8-9dd7-e5e7e61861cb.png)

**Comment by ttimot24** [comment]
It can be changed in the YouTubeVideo model 

> public function getThumbnail($no = 2).

The default number is changed to 0 in release 1.3 so the thumbnails now the same.
